# Generated by Django 3.2 on 2023-02-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='public',
            field=models.BooleanField(default=False, verbose_name='is public'),
            preserve_default=False,
        ),
    ]
