# Generated by Django 3.2 on 2023-02-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentspackage',
            name='public',
            field=models.BooleanField(default=True, verbose_name='is public'),
            preserve_default=False,
        ),
    ]
